language: node_js

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.2

node_js: '12'

addons:
  chrome: stable
  apt:
    packages:
      - xvfb

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run npm test; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist; fi
