language: node_js

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.2

node_js: '12'

addons:
  chrome: stable
  apt:
    packages:
      - xvfb
      
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "export DISPLAY=:99.0"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "sh -e /etc/init.d/xvfb start"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run npm test; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist; fi
